main: com.maverickmartyn.advanceyourlife.App
name: AdvanceYourLife
description: Adds lives earned from advancements, and enables spectator mode when you run out.
website: https://www.spigotmc.org/resources/advance-your-life.97793/
version: 1.0
author: MaverickMartyn
api-version: 1.19
permissions:
  advanceyourlife.ressurrect:
    description: Allows you to use the command /ressurrect
  advanceyourlife.getlives:
    description: Allows you to use the command /getlives
  advanceyourlife.awardlife:
    description: Allows you to use the command /awardlife
  advanceyourlife.givelife:
    description: Allows you to use the command /givelife    
commands:
   ressurrect:
      description: Ressurrects a player. Optional playername.
      usage: /ressurrect <playername?>
      permission: advanceyourlife.ressurrect
   getlives:
      description: Returns the lives of a player. Optional playername.
      usage: /getlives <playername?>
      permission: advanceyourlife.getlives
   awardlife:
      description: Awards a life to a player. Optional playername.
      usage: /awardlife <playername?>
      permission: advanceyourlife.awardlife
   givelife:
      description: Gives a life to a player from the sending player.
      usage: /givelife <playername?>
      permission: advanceyourlife.givelife
      
